- name: removes the firewall rule 
  hosts: localhost
  gather_facts: False
  vars_files:
    - vnf_vars/device.yml
  roles:
    - { role: get_instance }
    #  removes firewall rule
    - { role: configure_firewall, firewall_state: 'absent'  }

